### ISSUE TITLE
Constants documentation is invalid

### ISSUE THREAD

**Issue by mswezey23** [ethers-io/documentation#10]
Issue location: 
https://docs.ethers.io/ethers.js/html/api-utils.html#constants

Example:
```
utils . constants . AddressZero
The address 0x0000000000000000000000000000000000000000.
```

Invalid: `utils .`

When digging in the code base, `constants` is exported directly under the `ethers`. Not `utils`

**Comment by ricmoo** [comment]
Ah yes. This should be changed and added to the migration guide from v3 to v4.

Thanks! :)

**Comment by ricmoo** [comment]
Fixed. :)

**Comment by mswezey23** [comment]
Awesome, thanks :)
